export const ADDRESS_TYPE = {
    FIRSTNAME: 'FIRSTNAME',
    LASTNAME: 'LASTNAME',
    COUNTRY: 'COUNTRY',
    CITY: 'CITY',
    POSTCODE: 'POSTCODE',
    STREET: 'STREET',
    MOBILENUMBER: 'MOBILENUMBER',
}