
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from './redux/provider'
import { ClerkProvider } from '@clerk/nextjs'
import Main from "@/components/Main";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Choose weights
  style: ["normal", "italic"], // Optional: add styles
  variable: "--font-poppins", // Custom CSS variable
});


export const metadata: Metadata = {
  title: "Oragi Shopping Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ClerkProvider>

      <html lang="en" >

        <body className={poppins.variable} >

          <ReduxProvider>
            <Main>
              {children}
            </Main>
          </ReduxProvider>

          <script
            src="https://checkout.razorpay.com/v1/checkout.js"
            async
          ></script>
        </body>
      </html >
    </ClerkProvider>
  );
}
